# Generated by Django 5.2.8 on 2025-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите телеграм chat-id', max_length=50, null=True, verbose_name='Телеграм chat-id'),
        ),
    ]
