# Generated by Django 5.2.8 on 2025-11-24 21:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='Введите действие', verbose_name='Действие')),
                ('place', models.TextField(blank=True, help_text='Введите место выполнения', null=True, verbose_name='Место выполнения')),
                ('execution_time', models.TimeField(help_text='Задайте момент выполнения', verbose_name='Момент выполнения')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('frequency_days', models.PositiveIntegerField(default=1, help_text='Раз в сколько дней выполнять', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность (дней)')),
                ('execution_duration', models.DurationField(default=datetime.timedelta(seconds=120), help_text='Сколько времени занимает выполнение (ЧЧ:ММ:СС)', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=1)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='Длительность выполнения')),
                ('reward', models.CharField(blank=True, help_text='Чем себя вознаградить после выполнения', max_length=300, verbose_name='Вознаграждение')),
                ('owner', models.ForeignKey(help_text='Укажите обладателя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Обладатель')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, связанная с текущей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='tracker.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['execution_time'],
            },
        ),
    ]
