# Generated by Django 5.2.8 on 2025-11-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='name',
            field=models.CharField(default='Новая привычка', max_length=200, verbose_name='Название привычки'),
            preserve_default=False,
        ),
    ]
