# Generated by Django 5.2.8 on 2025-11-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_habit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Укажите, можно ли показывать данную привычку всем', verbose_name='Можно смотреть всем'),
        ),
    ]
